name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[release]')

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --python 3.10

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: "lts/*"

      - name: Install semantic-release plugins
        run: |
          npm install -g semantic-release \
                          @semantic-release/commit-analyzer \
                          @semantic-release/release-notes-generator \
                          @semantic-release/changelog \
                          @semantic-release/git \
                          @semantic-release/github \
                          @semantic-release/exec

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: semantic
        run: npx semantic-release

      - name: Build and publish to PyPI
        if: success()
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv build && uv publish --token "$PYPI_TOKEN"
